[tox]
envlist = py310, py311, py312, py313, py314, lint, coverage
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-cov
    pytest-anyio
    requests
    uvicorn
    fastapi
    httpx
commands =
    pytest --cov=pymcp --cov-report=term-missing

[testenv:lint]
deps =
    ruff
commands =
    ruff check .

[testenv:coverage]
deps =
    pytest
    pytest-cov
    pytest-anyio
    requests
    uvicorn
    fastapi
    httpx
commands =
    pytest --cov=pymcp --cov-report=xml
