"""Protocol helpers and typed wire models for JSON-RPC and MCP."""

from .errors import MCPError, MCPErrorCode
from .json_types import JSONArray, JSONObject, JSONValue, RPCId
from .jsonrpc import build_error_envelope, build_result_envelope, is_notification, validate_rpc_id
from .payload import PayloadFactory, get_payload_factory, negotiate_protocol_version
from .types import (
    CallToolRequestParams,
    CallToolResult,
    CancelledNotification,
    CancelledNotificationParams,
    ElicitationCompleteNotificationParams,
    ElicitationCreateParams,
    ElicitationResult,
    GetPromptRequestParams,
    GetPromptResult,
    InitializeParams,
    InitializeResult,
    JSONRPCError,
    JSONRPCNotification,
    JSONRPCRequest,
    JSONRPCResponse,
    ListPromptsResult,
    ListResourcesResult,
    ListRootsResult,
    ListToolsResult,
    ProgressNotification,
    ProgressNotificationParams,
    Prompt,
    PromptArgument,
    PromptMessage,
    ReadResourceRequestParams,
    ReadResourceResult,
    Resource,
    Root,
    ServerInfo,
    Task,
    TasksListResult,
    TextContent,
    TextResourceContents,
    Tool,
)
from .validate import validate_against_schema, validate_jsonrpc_request, validate_tool_arguments

__all__ = [
    "CallToolRequestParams",
    "CallToolResult",
    "CancelledNotification",
    "CancelledNotificationParams",
    "ElicitationCompleteNotificationParams",
    "ElicitationCreateParams",
    "ElicitationResult",
    "GetPromptRequestParams",
    "GetPromptResult",
    "InitializeParams",
    "InitializeResult",
    "JSONArray",
    "JSONRPCError",
    "JSONRPCNotification",
    "JSONRPCRequest",
    "JSONRPCResponse",
    "JSONObject",
    "JSONValue",
    "ListPromptsResult",
    "ListResourcesResult",
    "ListRootsResult",
    "ListToolsResult",
    "MCPError",
    "MCPErrorCode",
    "PayloadFactory",
    "ProgressNotification",
    "ProgressNotificationParams",
    "Prompt",
    "PromptArgument",
    "PromptMessage",
    "RPCId",
    "ReadResourceRequestParams",
    "ReadResourceResult",
    "Resource",
    "Root",
    "ServerInfo",
    "Task",
    "TasksListResult",
    "TextContent",
    "TextResourceContents",
    "Tool",
    "build_error_envelope",
    "build_result_envelope",
    "get_payload_factory",
    "is_notification",
    "negotiate_protocol_version",
    "validate_against_schema",
    "validate_jsonrpc_request",
    "validate_rpc_id",
    "validate_tool_arguments",
]
